# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Boat(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, length: int=None, at_sea: bool=None, type: str=None):  # noqa: E501
        """Boat - a model defined in Swagger

        :param id: The id of this Boat.  # noqa: E501
        :type id: str
        :param name: The name of this Boat.  # noqa: E501
        :type name: str
        :param length: The length of this Boat.  # noqa: E501
        :type length: int
        :param at_sea: The at_sea of this Boat.  # noqa: E501
        :type at_sea: bool
        :param type: The type of this Boat.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'length': int,
            'at_sea': bool,
            'type': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'length': 'length',
            'at_sea': 'at_sea',
            'type': 'type'
        }

        self._id = id
        self._name = name
        self._length = length
        self._at_sea = at_sea
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Boat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Boat of this Boat.  # noqa: E501
        :rtype: Boat
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Boat.


        :return: The id of this Boat.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Boat.


        :param id: The id of this Boat.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Boat.


        :return: The name of this Boat.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Boat.


        :param name: The name of this Boat.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def length(self) -> int:
        """Gets the length of this Boat.


        :return: The length of this Boat.
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length: int):
        """Sets the length of this Boat.


        :param length: The length of this Boat.
        :type length: int
        """
        if length is None:
            raise ValueError("Invalid value for `length`, must not be `None`")  # noqa: E501

        self._length = length

    @property
    def at_sea(self) -> bool:
        """Gets the at_sea of this Boat.

        false if boat is docked  # noqa: E501

        :return: The at_sea of this Boat.
        :rtype: bool
        """
        return self._at_sea

    @at_sea.setter
    def at_sea(self, at_sea: bool):
        """Sets the at_sea of this Boat.

        false if boat is docked  # noqa: E501

        :param at_sea: The at_sea of this Boat.
        :type at_sea: bool
        """
        if at_sea is None:
            raise ValueError("Invalid value for `at_sea`, must not be `None`")  # noqa: E501

        self._at_sea = at_sea

    @property
    def type(self) -> str:
        """Gets the type of this Boat.

        boat type  # noqa: E501

        :return: The type of this Boat.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Boat.

        boat type  # noqa: E501

        :param type: The type of this Boat.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
